// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwsMbPGzq73oMxqOfOz7673GwMGVzi-gg',
    appId: '1:848087329356:web:5e3c0c3baa9dcbee07e2e9',
    messagingSenderId: '848087329356',
    projectId: 'sagar-portfolio-d89f9',
    authDomain: 'sagar-portfolio-d89f9.firebaseapp.com',
    databaseURL: 'https://sagar-portfolio-d89f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sagar-portfolio-d89f9.firebasestorage.app',
    measurementId: 'G-YETL3C0X2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GL-bovcD_m-qC-sWLfR60I4luSc1qlk',
    appId: '1:848087329356:android:082206ed35d3d40407e2e9',
    messagingSenderId: '848087329356',
    projectId: 'sagar-portfolio-d89f9',
    databaseURL: 'https://sagar-portfolio-d89f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sagar-portfolio-d89f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg5hAUth8UNt5ZHKP9x3nlKreFDoXXb6c',
    appId: '1:848087329356:ios:5e0a552acb58871907e2e9',
    messagingSenderId: '848087329356',
    projectId: 'sagar-portfolio-d89f9',
    databaseURL: 'https://sagar-portfolio-d89f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sagar-portfolio-d89f9.firebasestorage.app',
    iosClientId: '848087329356-62s8l2o2plu1bm40aaard88s47qjl8s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sagarPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg5hAUth8UNt5ZHKP9x3nlKreFDoXXb6c',
    appId: '1:848087329356:ios:5e0a552acb58871907e2e9',
    messagingSenderId: '848087329356',
    projectId: 'sagar-portfolio-d89f9',
    databaseURL: 'https://sagar-portfolio-d89f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sagar-portfolio-d89f9.firebasestorage.app',
    iosClientId: '848087329356-62s8l2o2plu1bm40aaard88s47qjl8s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sagarPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwsMbPGzq73oMxqOfOz7673GwMGVzi-gg',
    appId: '1:848087329356:web:125c2bb42a38db0d07e2e9',
    messagingSenderId: '848087329356',
    projectId: 'sagar-portfolio-d89f9',
    authDomain: 'sagar-portfolio-d89f9.firebaseapp.com',
    databaseURL: 'https://sagar-portfolio-d89f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sagar-portfolio-d89f9.firebasestorage.app',
    measurementId: 'G-PC2EEH2CKC',
  );
}
